name: ray_dart
description: A library for sending debugging data to the Ray application.
version: 0.0.2
homepage: https://github.com/neonarray/ray-dart
repository: https://github.com/neonarray/ray-dart
topics:
  - debugging
  - logging

environment:
  sdk: ^3.6.0

dependencies:
  crypto: ^3.0.6
  http: ^1.2.2
  meta: ^1.16.0
  stack_trace: ^1.12.1
  uuid: ^4.5.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
